In [ ]:
# STRINGS AND CONTROL FLOW

In [ ]:
#EXAMPLE
flower= "Roses"
number= 12
print("Harriet gave "+ str(number) + " arrangements of " + flower + " to Daniel.")

Harriet gave 12 arrangements of Roses to Daniel.

In [ ]:
#EXAMPLE 2
clothes = "Denim"
number = 4
print("Michelle bought "+ str(number) + " pairs of " + clothes + " jackets for Efe.")

Michelle bought 4 pairs of Denim jackets for Efe.

In [ ]:
# WE CAN ALSO USE THE F-STRING METHOD TO COMBINE TEXT AND VARIABLES SEAMLESSLY AND MORE CONCISE
# THAN THE FIRST METHOD ABOVE.
#EXAMPLE 1
people= "gentiles"
number1= 5
number2 = 2
print(f'Jesus fed the {people} with {number1} loaves of bread and {number2} fish.')

Jesus fed the gentiles with 5 loaves of bread and 2 fish.

In [ ]:
#EXAMPLE1
people = "gentiles"
number1 = 5
number2 = 2
print('Jesus fed the {} with {} loaves of bread and {} fish.'.format(people,number1,number2))

Jesus fed the gentiles with 5 loaves of bread and 2 fish.

In [ ]:
#EXAMPLE2
people ='gentiles'
number1 = 5
number2 = 2
print('Jesus fed the {0} with {1} loaves of bread and {2} fish.'.format(people,number1,number2))

Jesus fed the gentiles with 5 loaves of bread and 2 fish.

In [ ]:
#EXAMPLE3
people= 'gentiles'
number1 = 5
number2 = 2
print('Jesus fed the {people1} with {number1} loaves of bread and {number2} fish.'.format(people1 = people, number1 = number1, number2 = number2))

Jesus fed the gentiles with 5 loaves of bread and 2 fish.

In [ ]:
#CONTROL FLOW: THESE ARE: IF STATEMENTS, LOOPS AND CONDITIONAL STATEMENTS.

#if statement
x= 10
if x > 0 and x % 2 == 0:
    print("x is an even number")

x is an even number

In [ ]:
#EXAMPLE
y= 12
if y> 3 and y % 2==0:
    print('y is an even number')

y is an even number

In [ ]:
x= 12
if x>0 and x*1==12:
    print('x is a divisor of 12')

x is a divisor of 12

In [ ]:
x= 15
if x>0 and x-2==0:
    print('x is an even number')
else:
    print('x is an odd number')

x is an odd number

In [ ]:
#NESTED IF
#EXAMPLE
age= 14
if age >= 18:
    if age < 21:
        print('You are an adult but not allowed to drink')
    else:
        print('You are an adult and allowed to drink')
else:
        print('You are underage')

You are underage

In [ ]:
#EXAMPLE2
age = 18
if age >=18:
    if age <=25:
        print('You have your drivers licence but not allowed to drive')
    else:
        print('You have your drivers licence and are allowed to drive')
else:
        print('You are underage')

You have your drivers licence but not allowed to drive

In [ ]:
#IF-ELIF-ELSE
age= 17
if age>= 17 and age >21:
    print('You are a model but cannot walk on the runway')
elif age>=17 and age>= 21:
    print('You are a model and can walk on the runway')
elif age >=17 or age >21:
    print('You are a model')
else:
    print('You are underage')

You are a model

In [ ]:
#EXAMPLE 2: SCHOOL GRADING SYSTEM
score= 98
if score >= 90:
   print('A')
elif score >=80:
   print('B')
elif score >=70:
    print('C')
else:
     print('Fail')

A

In [ ]:
#TENARY OPERATORS
#EXAMPLE
score = 49
result= "Fail" if score < 50 else "Pass"
print(result)

Fail

In [ ]:
#LOOPS: WE HAVE TWO LOOPS.1.FOR LOOP AND 2. WHILE LOOP

#FOR LOOP
#EXAMPLE
list_= ['apple','banana','orange','mango']
for item in list_:
    print(item)

apple
banana
orange
mango

In [ ]:
# ITERATING OVER A LIST TO PRINT ODD NUMBERS
list_= [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
for i in list_:
     if i % 2 ==1:
             print(i)

1
3
5
7
9
11
13
15

In [ ]:
list_= ['tomatoe','carrot','green bell peppers','yam','onion','cassava','potatoe','cocoyam']
for i in list_:
        print(i)

tomatoe
carrot
green bell peppers
yam
onion
cassava
potatoe
cocoyam

In [ ]:
#ITERATING OVER A DICTIONARY
person= {'name': 'Joseph', 'age': 34, 'city': 'New York'}
for key, value in person.items():
                              print(f'{key}:{value}')

name:Joseph
age:34
city:New York

In [ ]:
#iterating to get sum
list_= [20,30,40,50,60,70,80]
total= 0
for item in list_:
    total += item
    print(total)

20
50
90
140
200
270
350

In [ ]:
#ITERARTING OVER A DICTIONARY
person= {'name':'Jonathan', 'age': 15, 'city':'Tokyo'}
for key, value in person.items():
                   print(f'{key}:{value}')

name:Jonathan
age:15
city:Tokyo

In [ ]:
#LOOPING AND PRINTING A VALUE
i=1
while i<=10:
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9
10

In [ ]:
#LOOPING OVER A LIST AND PRINTING THE ITEMS IN THE LIST
emma= ['Apple','Banana','Orange','Mango']
i=0
while i<=3:
    print(emma[i])
    i+=1

Apple
Banana
Orange
Mango

In [ ]:
#FUNCTIONS: THESE ARE BLOCKS OF CODE THAT WHEN CREATED CAN BE USED OVER AND OVER AGAIN.
#TO CALL A FUNCTION:
#1. DEFINITION OF THE FUNCTION
def add(a,b)
#2. NAME THE FUNCTION(add)
# 3. PARAMETERS OF THE FUNCTIONS (a,b)
# 4. CODE BLOCK ( C= A+B )
# 5. OUTCOME YOU WANT TO SEE ( RETURN C)

In [ ]:
def add(a,b):
    c=a+b
    return c

In [ ]:
add(6,10)

16

In [ ]:
def subt(a,b):
    c=b-a
    return c

In [ ]:
subt(12,20)

8

In [ ]:
def mult(a,b):
    c=a*b
    return c

In [ ]:
mult(9,2)

18

In [ ]:
#FUNCTION TO GREET A USER
def greet(name):
    return f"Hello, {name}!"

In [ ]:
# CALLING THE FUNCTION
message= greet('Stephanie')
print(message)

Hello, Stephanie!

In [ ]:
# FINDING THE SUM AND PRODUCT OF TWO NUMBERS
def sum_and_product(a,b):
    c= a+b, a*b
    return c

In [ ]:
result= sum_and_product(3,4)
print('sum', result[0])
print('product', result[1])

sum 7
product 12

In [ ]:
# lAMBDA FUNCTION: THE LAMBDA FUNCTION IS A SMALL ANONYMOUS FUNCTION WRITTEN IN ONE LINE.

In [ ]:
# ADDING NUMBERS
add = lambda x,y: x+y
print(add(3,5))

8

In [ ]:
# SUBTRACTING
subtract = lambda x,y: y-x
print(subtract(9,15))

6

In [ ]:
mult= lambda x,y:x*y
print(mult(2,5))

10

In [ ]:
# USING THE LAMBDA FUNCTION WITH DICTIONARIES
students= [{'name':'Ransford','score':75}, {'name':'Samira','score':'90'}
          ]
sorted_students= sorted(students,key=lambda x:x['name'], reverse= True)
print(sorted_students)

[{'name': 'Samira', 'score': '90'}, {'name': 'Ransford', 'score': 75}]

In [ ]:
students= [{'name':'Xena','score':75}, {'name':'Abel','score':90}]
sorted_students= sorted(students, key=lambda x:x['score'])
print(sorted_students)

[{'name': 'Xena', 'score': 75}, {'name': 'Abel', 'score': 90}]

In [ ]:
# BUILT- FUNCTIONS
# 1. MAPPING: THIS MATCHES EACH ITEM IN THE SEQUENCE OR ITERABLE AND RETURNS A NEW ITERABLE WITH THE RESULTS.
numbers= [1,2,3,4,5]
squared= map(lambda x:x**2, numbers)
print(list(squared))

[1, 4, 9, 16, 25]

In [ ]:
#CONVERTING TEMPERATURES FROM CELSIUS T FAHRENHEIT USING MAPPING
temps_celsius= [0, 10, 20 ,30, 40]
temps_fahrenheit= map(lambda c:(c* 9/5) + 32, temps_celsius)
print(list(temps_fahrenheit))

[32.0, 50.0, 68.0, 86.0, 104.0]

In [ ]:
# CAPITALISING THE FIRST LETTER IN A STRING USING MAPPING.
words= ['magnolias', 'hibscus', 'lillies']
capitalized_words= map(lambda w:w.capitalize(), words)
print(list(capitalized_words))

['Magnolias', 'Hibscus', 'Lillies']

In [ ]:
# FILTER FUNCTION: THIS WILL FITER THE ELEMENTS IN A LIST TO SEE WHICH ONE ONES SATISFY THE CONDITION GIVEN.
numbers = [1, 2, 3, 4, 5, 6]
filtered_numbers = filter(lambda x:x % 2 ==0, numbers)
print(list(filtered_numbers))

[2, 4, 6]

In [ ]:
# FILTERING OUT NEGATIVE NUMBERS FROM A LIST OF NUMBERS.
numbers = [4, 8, -2, 3, -6, -12]
neg_numbers = filter(lambda x:x > 0, numbers)
print(list(neg_numbers))

[4, 8, 3]

In [ ]:
# REDUCE FUNCTION: THIS COMBINES THE ELEMENTS IN AN ITERABLE IN A SINGLE VALUE.
#FINDING THE PRODUCT OF ELEMENTS IN A LIST
from functools import reduce
numbers = [1, 2, 3, 4, 5]
product = reduce(lambda x, y:x*y, numbers)
print(product)

120

In [ ]:
numbers= [1, 2, 3, 4, 5, 6]
expo_numbers = reduce(lambda x, y:x + y, numbers)
print(expo_numbers)

21

In [ ]:
numbers= [2, 5, 10, 4, 20]
max_num= reduce(lambda x, y:x if x>y else y, numbers)
print(max_num)

20

In [26]:
# SUM FUNCTION: returns the total or sum of all elements in the list or iterable.
numbers= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
total= sum(numbers)
print(total)

55

In [27]:
# MAXIMUM FUNCTION: THIS RETURNS THE MAXIMUM ELEMENT IN THE LIST/ITERABLE.
numbers= [2, 4, 6]
max_num= max(numbers)
print(max_num)

6

In [28]:
#FINDING THE LONGEST STRING IN A LIST.
strings= ['plantain', 'yam', 'pineapple', 'ginger ale','pomegranate']
longest_string= max(strings, key=len)
print(longest_string)

pomegranate

In [29]:
#MINMUM FUNCTION: THIS RETURNS THE MINIMUM OR LOWEST ELEMENT IN AN ITERABLE.
numbers= [0, 2, 6, 18]
min_num= min(numbers)
print(min_num)

0

In [30]:
 #FINDING THE MINMUM VALUE IN A DICTIONARY
scores= {'Nawal':56, 'Ruwaida': 78, 'Azara': 90}
min_score = min(scores.values())
print(min_score)

56

In [ ]:
# PANDAS:

In [31]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [33]:
# CREATING A SERIES FROM PYTHON LIST
s =pd.Series([1, 2, 3, 'Angel','Efe', 4])
print(s)

0        1
1        2
2        3
3    Angel
4      Efe
5        4
dtype: object

In [34]:
# CREATING A DATAFRAME FROM A DICTIONARY
df= {'name':['Hocket','Ahmed','Sarah'], 'age':[23,35,40], 'location':['Istanbul', 'Kuwait', 'Doha']}
data= pd.DataFrame(df)
print(data)

     name  age  location
0  Hocket   23  Istanbul
1   Ahmed   35    Kuwait
2   Sarah   40      Doha

In [35]:
#using the indexing menthod
x = [1,2,3,4,5,'apple','tissue']
# ACCESSING ELEMENTS IN A SERIES
print(x[5])     #accessing the fifth element in the series

apple

In [36]:
# using the slicing method
x= {'name':['Hocket','Ahmed','Sarah'], 'age':[23,35,40], 'location':['Istanbul', 'Kuwait', 'Doha']}
df = pd.DataFrame(x)
print(df)

# Slicing a DataFrame
df[['name']]                    #Accessing a column

df[['location']]

     name  age  location
0  Hocket   23  Istanbul
1   Ahmed   35    Kuwait
2   Sarah   40      Doha

   location
0  Istanbul
1    Kuwait
2      Doha

In [ ]:
# @title
# DATA COMBINATION: THIS IS THE PROCESS OF JOINING, MERGING,
# AND CONCATENATING MULTIPLE PANDAS DATA STRUCTURE INTO A SINGLE DATA STRUCTURE.
# 1. CONCATENATE FUNCTION: USED TO COMBINE TWO OR MORE DATAFRAMES WITH THE SAME COLUMNS EITHER VERTICALLY OR
# HORIZONTALLY.
# if your dataframes do not have the same columns you cannot use the concate function.

In [37]:
# EXAMPLES USING THE CONCATENATE FUNCTION
df_1 = pd.DataFrame({'A':[4, 2, 6], 'B':['m', 'n', 'o']})
print(df_1)

   A  B
0  4  m
1  2  n
2  6  o

In [38]:
df_2 = pd.DataFrame({'A':[45, 8, 9], 'B':['x', 'y', 'z']})
print(df_2)

    A  B
0  45  x
1   8  y
2   9  z

In [5]:
import pandas as pd

In [4]:
# VERTICAL CONCATENATION(ROW-WISE)
df_1 = pd.DataFrame({'A':[4, 2, 6], 'B':['m', 'n', 'o']})
df_2 = pd.DataFrame({'A':[45, 8, 9], 'B':['x', 'y', 'z']})
vertical_com = pd.concat([df_1,df_2], axis=0, keys=['df_1', 'df_2'])
vertical_com

         A  B
df_1 0   4  m
     1   2  n
     2   6  o
df_2 0  45  x
     1   8  y
     2   9  z

In [11]:
vertical_com.loc['df_1', 0][0]

/tmp/ipykernel_183/3061867438.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  vertical_com.loc['df_1', 0][0]

np.int64(4)

In [12]:
# Specifying each columns and their respective values or elements
vertical_com.loc['df_1', 0]['A':'B']

A    4
B    m
Name: (df_1, 0), dtype: object

In [5]:
#.loc or .iloc
vertical_com.loc['df_1', 0]

A    4
B    m
Name: (df_1, 0), dtype: object

In [6]:
# USING THE IGNORE INDEX FUNCTION IT DOES NOT SHOW THE DF_1 AND DF_2 LABELS IN THE OUTPUT
vertical_com = pd.concat([df_1, df_2], axis=0, ignore_index=True)
vertical_com

    A  B
0   4  m
1   2  n
2   6  o
3  45  x
4   8  y
5   9  z

In [7]:
# HORIZONTAL CONCATENATION: WE CHANGE THE AXIS FROM 0 TO 1.
horizontal_com= pd.concat([df_1, df_2], axis=1, keys=['df_1','df_2'])
horizontal_com

  df_1    df_2
     A  B    A  B
0    4  m   45  x
1    2  n    8  y
2    6  o    9  z

In [8]:
# EXAMPLE
accra=pd.DataFrame({'Town':['Cirlce', 'Madina', 'East Legon'], 'Humidity':[32, 29, 34], 'Temperature':[28, 30, 25]})

kumasi=pd.DataFrame({'Town':['Kejetia', 'Amakom', 'Mantia'], 'Humidity':[27, 39, 36], 'Temperature':[30, 26, 24]})

In [9]:
df_3= pd.concat([accra, kumasi], ignore_index=True)
df_3

         Town  Humidity  Temperature
0      Cirlce        32           28
1      Madina        29           30
2  East Legon        34           25
3     Kejetia        27           30
4      Amakom        39           26
5      Mantia        36           24

In [10]:
df_4= pd.DataFrame({'Windspeed':[8,5,2,4,6,7,9,2,16]})
df_4

   Windspeed
0          8
1          5
2          2
3          4
4          6
5          7
6          9
7          2
8         16

In [11]:
# to combine windspeed to the accra and kumasi we concate
vertical_com=pd.concat([df_3, df_4], ignore_index=True, axis=0)
vertical_com

          Town  Humidity  Temperature  Windspeed
0       Cirlce      32.0         28.0        NaN
1       Madina      29.0         30.0        NaN
2   East Legon      34.0         25.0        NaN
3      Kejetia      27.0         30.0        NaN
4       Amakom      39.0         26.0        NaN
5       Mantia      36.0         24.0        NaN
6          NaN       NaN          NaN        8.0
7          NaN       NaN          NaN        5.0
8          NaN       NaN          NaN        2.0
9          NaN       NaN          NaN        4.0
10         NaN       NaN          NaN        6.0
11         NaN       NaN          NaN        7.0
12         NaN       NaN          NaN        9.0
13         NaN       NaN          NaN        2.0
14         NaN       NaN          NaN       16.0

In [12]:
pd.concat([df_3,df_4], ignore_index=True, axis=1)

            0     1     2   3
0      Cirlce  32.0  28.0   8
1      Madina  29.0  30.0   5
2  East Legon  34.0  25.0   2
3     Kejetia  27.0  30.0   4
4      Amakom  39.0  26.0   6
5      Mantia  36.0  24.0   7
6         NaN   NaN   NaN   9
7         NaN   NaN   NaN   2
8         NaN   NaN   NaN  16